version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:19.0.1

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: java --version
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

        # Install deps for Circle CI
      - run: mvn clean install -Dmaven.test.skip=true
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests! and gen code coverage
      - run: mvn integration-test

      - store_test_results:
          path: target/surefire-reports
          
      - run:
          name: Configure sonar projectBaseDir
          command: cp -R ~/repo /Users/distiller
      - run:
          name: Copy code coverage file
          command: cp target/surefire-reports/*.xml /Users/distiller/project
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=sbouhaddi_file-management    
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
